relations:
- src: 1
  dst: 2
  type: 师徒
  symmetric: true
- src: 1
  dst: 3
  type: 师徒
  symmetric: true
- src: 1
  dst: 4
  type: 师徒
  symmetric: true
- src: 2
  dst: 3
  type: 敌对
  symmetric: true
- src: 2
  dst: 4
  type: 利用
  symmetric: false
- src: 3
  dst: 4
  type: 利用
  symmetric: false
- src: 5
  dst: 2
  type: 暗中合作
  symmetric: true
- src: 5
  dst: 1
  type: 敌对
  symmetric: true
