relations:
- src: 1
  dst: 2
  type: 互相猜忌
  symmetric: true
- src: 1
  dst: 3
  type: 主仆
  symmetric: false
- src: 1
  dst: 4
  type: 表面客气
  symmetric: true
- src: 2
  dst: 3
  type: 秘密情人
  symmetric: true
- src: 2
  dst: 4
  type: 互相敌视
  symmetric: true
- src: 3
  dst: 4
  type: 表面尊敬
  symmetric: true
