relation_types:
- type: 互相猜忌
  is_contact: true
  symmetric: true
- type: 主仆
  is_contact: true
  symmetric: false
- type: 表面客气
  is_contact: true
  symmetric: true
- type: 秘密情人
  is_contact: false
  symmetric: true
- type: 互相敌视
  is_contact: true
  symmetric: true
- type: 表面尊敬
  is_contact: true
  symmetric: true
