relation_types:
- type: trust
  is_contact: true
  symmetric: false
- type: alliance
  is_contact: true
  symmetric: true
- type: rivalry
  is_contact: true
  symmetric: true
- type: distrust
  is_contact: false
  symmetric: false
- type: antagonistic
  is_contact: true
  symmetric: true
- type: secret_love
  is_contact: false
  symmetric: false
