relations:
- src: 0
  dst: 4
  type: trust
  symmetric: false
- src: 1
  dst: 2
  type: alliance
  symmetric: true
- src: 1
  dst: 3
  type: rivalry
  symmetric: true
- src: 1
  dst: 4
  type: distrust
  symmetric: false
- src: 2
  dst: 3
  type: antagonistic
  symmetric: true
- src: 3
  dst: 4
  type: trust
  symmetric: true
- src: 4
  dst: 3
  type: secret_love
  symmetric: false
