relations:
- src: 1
  dst: 2
  type: 庇护
  symmetric: false
- src: 2
  dst: 1
  type: 感激
  symmetric: false
- src: 3
  dst: 4
  type: 交易
  symmetric: false
- src: 4
  dst: 2
  type: 追捕
  symmetric: false
- src: 1
  dst: 3
  type: 提防
  symmetric: true
- src: 1
  dst: 4
  type: 提防
  symmetric: true
- src: 2
  dst: 3
  type: 敌意
  symmetric: true
- src: 2
  dst: 4
  type: 敌意
  symmetric: true
- src: 3
  dst: 2
  type: 觊觎
  symmetric: false
